### ISSUE TITLE
[Bug] os.statvfs is only available on Unix-like systems

### ISSUE THREAD

**Issue by MIAIONE** [Tinche/aiofiles#173] opened 2023-08-10 10:25 UTC
os.statvfs is only available on Unix-like systems

"statvfs = wrap(os.statvfs)" does not check if the operating system supports this operation. On Windows, this feature does not exist.

**Comment by Tinche** [comment] 2023-08-10 10:50
Duplicate of #171

**Closed by Tinche** 2023-08-10 10:50 UTC
